services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blogger
      MYSQL_USER: blogger
      MYSQL_PASSWORD: blogger
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql